### ISSUE TITLE
Как собираете картинки?

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-forum-content-ru#162]
толкнулись с проблемой распределения картинок по блокам
Решили что наилучшим способом будет папка 
/block
../i
....block__element.jpg

Есть ли технология под сборку картинок? Я про bem-tools

**Comment by tadatuta** [comment]
@pavelpower Если я правильно тебя понял, то ты в сорцах хочешь хранить картинки в папке блока в подпапке `i`?
Тогда `project-stub` уже решает твою задачу ;)
Отвечает за это дело [borschik](http://ru.bem.info/tools/optimizers/borschik/), вызов которого встроен в `bem-tools`.
Кстати, он умеет не только правильно подменять пути, но делать [фриз](http://ru.bem.info/tools/optimizers/borschik/freeze/), включая не только умную замену путей, но и инлайнинг прямо в HTML при необходимости.

**Comment by pavelpower** [comment]
@tadatuta да вроде как сборщику умеет это делать. Но я пока не понимаю как сделать так, чтобы bem-tools по deps брал нужные картинки.
в level.js надо указать доп технологию?

**Comment by tadatuta** [comment]
@pavelpower в смысле «брал»? что подразумевает это действие?
если у тебя в CSS блоков, которые попали в сборку по desp, окажутся ссылки на картинки, то пути автоматически будет перепианы на правильные в зависимости от конфига `.borschik` и переменной окружения `YENV`.

**Comment by pavelpower** [comment]
@tadatuta  как мне борщику скормить css

```css
.b-legend__button_menu {
  width: 34px;
  height: 15px;
  background: url("../../app/view.blocks/ecords-buttons-menu/i/records-buttons-menu.gif") no-repeat;
}
```

чтобы он взял картинку по этому пути и положил ее в

`img/magesrecords-buttons-menu.gif`

да еще и заморозил?
