### ISSUE TITLE
Верстка для разных устройств с БЭМ

### ISSUE THREAD

**Issue by Bumerang47** [bem/bem-forum-content-ru#347]
А есть какие ни будь кейсы, в bem-tools для верстки одного проекта под разные устройтсва, разных форматов экрана? Не имея в виду атрибуты 'm', 's' в компонентах, а как оперативно делить один проект на разные стили, может автоматически подключать разные файлы стилей для разных устройств при сборки или еще что ни будь?

**Comment by zxqfox** [comment]
Вопрос возник из-за наличия уровней в bem-components с реализациями под разные платформы?

https://github.com/bem/bem-components/tree/v2/desktop.blocks/input
https://github.com/bem/bem-components/tree/v2/touch.blocks/input

Или это и есть ответ? ;-)

**Comment by Bumerang47** [comment]
:) Да, частично ответ, спасибо. 
А если для своих блоков, не компонентных, как делить стили? Так например не только для desktop/touch, а разных соотношений сторон (4:3; 16:9), мобильных/планшетов. Применяя адаптивную верстку, что можно посоветовать?

**Comment by zxqfox** [comment]
Можно точно так же распилить на уровни. Но для разных соотношений сторон — на мой взгляд нет смысла делить, потому что нет случаев, когда в сборку попадут только стили для `4:3` или только `16:9`. Стили будут всегда вместе. Для `@media` могу посоветовать использовать хелперы препроцессоров (того же стайлуса).

Например (если меня не побъет @tadatuta), можно делать так в базовом файле:
```less
    // breakpoints
    @bpMobile:  480px;
    @bpTablet:  768px;  @bpPreTablet: @bpTablet - 1;
    @bpDesktop: 1024px; @bpPreDesktop: @bpDesktop - 1;
    @bpWide:    1440px; @bpPreWide: @bpWide - 1;

    // presets
    @thin: ~"screen and (max-width: @{bpMobile})";; // [0-480]
    @mobile: ~"screen and (max-width: @{bpPreTablet})"; // [0-767]
    @tablet: ~"screen and (min-width: @{bpTablet}) and (max-width: @{bpPreDesktop})"; // [768-1023]
    @desktop: ~"screen and (min-width: @{bpDesktop}) and (max-width: @{bpPreWide})"; // [1024-1439]
    @wide: ~"screen and (min-width: @{bpWide})"; // [1440-∞)
```

И в ваших блоках:
```less
    // usage
    .my-block {
        width: 200px;
        @media @wide {
            width: 300px;
        }
        @media @tablet {
            width: 100px;
        }
        @media @mobile {
            display: none;
        }
    }
```

На выходе будет:
```css
.my-block {
  width: 200px;
}
@media screen and (min-width: 1440px) {
  .my-block {
    width: 300px;
  }
}
@media screen and (min-width: 768px) and (max-width: 1024px - 1) {
  .my-block {
    width: 100px;
  }
}
@media screen and (max-width: 768px - 1) {
  .my-block {
    display: none;
  }
}
```
