### ISSUE TITLE
Большая проблема минимизации css

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-forum-content-ru#540]
Добре коллеги!

Случайно выяснил, что борщик минимизирует css как-то не очень хорошо. 

Работаю с *enb-borshchik*

Дело в том, что он не производит семантическое объединение классов. Которое просто необходимо для тех случаев когда хотим использовать base64 в css.

Что же это такое *семантическое объединение*?

Рассмотрим пример:

Есть файл `a.css`
```css
.a {
    left: 20px;
    background: #red;
}

.b {
    left: 1px;
}

.k .a {
    left: 20px;
    background: #red;
}

.a {
    right: 20px;
    left: 1px;
    background: url(./resources/images/1280x720-tv-background__overlay_info.png);
}

.b {
    left: 2px;
}

.k .a {
    right: 20px;
    left: 1px;
    background: url(./resources/images/1280x720-tv-background__overlay_info.png);
}
```

После семантического объединения должны получить следующее:
```css
.a, .k .a{
    right:20px;
    left:1px;
    background:url(resources/images/1280x720-tv-background__overlay_info.png)
}
.b { left:2px }
```

Делать это умеет библиотека:
https://www.npmjs.com/package/clean-css

с включенной опцией `--semantic-merging`

Вопрос - как решить задачу семантической сборки css для enb? 

Видел, что есть 
[![NPM version](https://badge.fury.io/js/borschik-tech-cleancss.png)](http://badge.fury.io/js/borschik-tech-cleancss)

Может уже решали данную проблему до меня?
