### ISSUE TITLE
Замечание к CSS при переопределении [проблемы которых у тебя может не быть]

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-forum-content-ru#653]
В нашем проекте где используем БЭМ заметили интересное поведение для некоторых свойств CSS при переопределении и при семантическом объединении борщиком.

```javascript
[borschik,
   techOptions: {
       semanticMerging: true
   },
//...
]
```

Это проявляется на старых браузерах или браузере с обрезанным функционалом.

Если свойство, к примеру `background` объявить в обобщенном виде, а не отдельно по параметрам, пример:

```css
.block {
    background: url(i/arrow.png) center center no-repeat;
}
```

При это в дальнейшем переопределить одно из указанных свойств

```css
.block {
    background-image: url(i/yellow-arrow.png);
}
```

То переопределение может сработать не корректно, и часто поведение (особенно на short-браузерах) будет похоже на гейзенбаг.

Решение пока нашли в том, что все свойства объявляем подробно:

```css
.block {
    background-image: url(i/arrow.png);
    background-position: center center;
    background-prepeat: no-repeat;
}
```
