### ISSUE TITLE
Блок select

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#820]
Всем привет! Какой файл нужно править, чтобы при выботе в блоке select какого-то значения, в кнопку попадало не значение text блока select, а icon? Второе, нужно избавиться от __tick, а просто выделять цветом.

**Comment by tadatuta** [comment]
Избавиться от `__tick` можно в стилях:
```css
.icon.select__tick {
    display: none;
}

.select.select_theme_islands .select__button.button_size_m .button__text {
    margin: 0;
    padding: 0 1em;
}
```

А за обновление кнопки отвечает метод `_updateButton`, так что его потребуется переопределить как-то так (решение ни в коем случае не тянет на production-ready, а просто иллюстрирует направление мысли):
```js
modules.define('select', ['i-bem__dom'], function(provide, BEMDOM, Select) {

Select.decl({ block: this.name, modName: 'mode', modVal: 'check' }, {
    _updateButton : function() {
        var icon = this._button.findBlockInside('icon'),
            checkedItems = this._getCheckedItems();

        if (checkedItems.length) {
            var checkedIconElem = checkedItems[0].findBlockInside('icon').domElem.clone();

            this._button.elem('text').hide();
            BEMDOM.replace(icon.domElem, checkedIconElem).show();
        } else {
            this._button
                .setText(this.params.text)
                .elem('text').show();
                
            icon.domElem.hide();
        }
    }
});

provide(Select);

});
```
