### ISSUE TITLE
Закрытие модального окна по крестику

### ISSUE THREAD

**Issue by lavezzi1** [bem/bem-forum-content-ru#864]
С удивлением обнаружил отсутствие этой функции. Прощу помощи в расширении функционала стандартного модального окна в bem-components.

**Comment by tadatuta** [comment]
@lavezzi1 

```js
// _has-close/modal_has-close.js

modules.define('modal', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl({ block: this.name, modName: 'has-close', modVal: true }, {}, {
    live: function() {
        this.liveBindTo('close', 'click', function() {
            this.delMod('visible');
        });
    }
}
));

});

// _has-close/modal_has-close.deps.js

({
    shouldDeps: [{ elem: 'close' }]
})

// _has-close/modal_has-close.bemhtml.js

block('modal').mod('has-close', true).elem('content').content()(function() {
    return [
        { elem: 'close' },
        applyNext()
    ];
});
```

__close/modal__close.css
```css
.modal__close {
    width: 14px;
    height: 14px;

    position: absolute;
    top: 15px;
    right: 15px;

    cursor: pointer;

    background: url(modal__close.svg) no-repeat;
}
```

__close/modal__close.svg

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14"><path d="M14 .7l-.7-.7L7 6.3.7 0 0 .7 6.3 7 0 13.3l.7.7L7 7.7l6.3 6.3.7-.7L7.7 7z"/></svg>
```

Если есть необходимость вызывать динамическое обновление контента для формы с крестиком, потребуется еще переопределить метод `setContent`, чтобы крестик не удалялся.
