### ISSUE TITLE
Конфиг gemini для мобильных браузеров с использованием browserstack

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [bem/bem-forum-content-ru#934]
Как настроить gemini на тестирование в 
Safari 9 (iOS 9)
Chrome 45 (Android 6) 
Chrome 45 (Android 5)
с использованием сервиса browserstack? 

такого вида конфиг:
```
browsers:
  safari:
    desiredCapabilities:
        os: "IOS"
        os_version: "9"
        browserName: "safari"
        version: "9"
```
дает ошибку:

```
Cannot launch browser safari:
[init({"os":"IOS","os_version":"9","browserName":"safari","version":"9","browserstack.local":true})] The environment you requested was unavailable.
```
